export HTTP_RPOXY=127.0.0.1:8118
export HTTPS_RPOXY=127.0.0.1:8118

export PATH="/usr/local/go/bin:$HOME/.go/bin:$HOME/.local/bin:$PATH"
. "$HOME/.cargo/env"
export GOPATH="$HOME/.go"
export EDITOR="/bin/nvim"
