theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
a = ["move_char_right", "insert_mode"]